### ISSUE TITLE
Design suggestion: change ASTNode variants to contain concrete structs

### ISSUE THREAD

**Issue by khionu** [sqlparser-rs/sqlparser-rs#40] opened 2019-01-26 21:21 UTC
As is, the example below can be a necessary evil. Using separate, concrete structs allows the data to be passed as a single value.
```rs
fn main() {
    // ...
    match sql_ast {
        SQLSelect { projection, relation, joins, selection, 
                    order_by, group_by, having, limit } =>  {
            select(projection, relation, joins, selection,
                   order_by, group_by, having, limit, &mut out_ts);
        },
        _ => {}
    }
}

fn select(projection: Vec<ASTNode>, relation: Option<Box<ASTNode>>, joins: Vec<Join>,
          selection: Option<Box<ASTNode>>, order_by: Option<Vec<SQLOrderByExpr>>,
          group_by: Option<Vec<ASTNode>>, having: Option<Box<ASTNode>>, limit: Option<Box<ASTNode>>,
          out_ts: &mut TokenStream) {
    // ...
}
```

**Comment by nickolay** [comment] 2019-01-30 02:18
FWIW, I did this to `SQLSelect` locally in [an experiment to make the AST more strongly typed](https://github.com/nickolay/sqlparser-rs/commit/48b44bad436fcd5943ec6b91ae39771146b532d8#diff-aead2c4cdd17ba10d13b08bdc4418406R147), because it lets me to use the struct both from an ASTNode (for a subquery) and from an SQLStatement (as a top-level statement).

**Comment by nickolay** [comment] 2019-05-07 01:41
The branch I mentioned above has been merged, so SQLSelect / SQLQuery are separate structs now. Some ASTNode variants are still inlined though, but I'm not sure it makes sense to mechanically create a separate struct for each variant. Are there any variants where this is still a problem?

**Comment by alamb** [comment] 2021-12-12 21:58
Closing as a dupe of #311 as suggested in https://github.com/sqlparser-rs/sqlparser-rs/issues/311#issuecomment-991838838

**Closed by alamb** 2021-12-12 21:58 UTC
