### ISSUE TITLE
Incorrect parsing literals that consisting of digits and letters, beginning with digits

### ISSUE THREAD

**Issue by DiamondMofeng** [sqlparser-rs/sqlparser-rs#804] opened 2023-02-03 14:11 UTC
It seems when parsing a literal beginning with digits, the sql parser simply ends this token when meets a non-numeric character

see https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/tokenizer.rs#L547

For example, `123foobar` would be parsed into a number token `123` and a word token `foobar` instead of one word token `123foobar`.

And `123foobar456` would be parsed into `123` and `foobar456`

**Comment by DiamondMofeng** [comment] 2023-02-03 14:29
Althrough nodody would name their columns like `1col` `00column`, mysql does allow this.

``` bash
MariaDB [(none)]> CREATE DATABASE test;
Query OK, 1 row affected (0.000 sec)

MariaDB [(none)]> use test;
INSERT INTO my_table VALUES (3,4,5);

SELECT * FROM my_table;
SELECT 1col FROM my_table
Database changed
MariaDB [test]> CREATE TABLE my_table (
    -> id int,
    -> 1col int,
    ->     2col int
    -> );
Query OK, 0 rows affected (0.029 sec)

MariaDB [test]>
MariaDB [test]> INSERT INTO my_table VALUES (1,2,3);
Query OK, 1 row affected (0.005 sec)

MariaDB [test]> INSERT INTO my_table VALUES (2,3,4);
Query OK, 1 row affected (0.003 sec)

MariaDB [test]> INSERT INTO my_table VALUES (3,4,5);
Query OK, 1 row affected (0.007 sec)

MariaDB [test]>
MariaDB [test]> SELECT * FROM my_table;
+------+------+------+
| id   | 1col | 2col |
+------+------+------+
|    1 |    2 |    3 |
|    2 |    3 |    4 |
|    3 |    4 |    5 |
+------+------+------+
3 rows in set (0.000 sec)

MariaDB [test]> SELECT 1col FROM my_table
    -> ;
+------+
| 1col |
+------+
|    2 |
|    3 |
|    4 |
+------+
3 rows in set (0.000 sec)

MariaDB [test]>

```

**Comment by DiamondMofeng** [comment] 2023-02-03 14:37
```rust
fn main() {
    use sqlparser::dialect::GenericDialect;
    use sqlparser::parser::Parser;

    let sql = "SELECT 123foobar FROM table1";

    let dialect = GenericDialect {}; // or AnsiDialect, or your own dialect ...
    let ast = Parser::parse_sql(&dialect, sql).unwrap();
    println!("AST: {:?}", ast);
}
```

```
AST: [Query(Query { with: None, body: Select(Select { distinct: false, top: None, projection: [
    ExprWithAlias { expr: Value(Number("123", false)), alias: Ident { value: "foobar", quote_style: None } }
], into: None, from: [TableWithJoins { relation: Table { name: ObjectName([Ident { value: "table1", quote_style: None }]), alias: None, args: None, with_hints: [] }, joins: [] }], lateral_views: [], selection: None, group_by: [], cluster_by: [], distribute_by: [], sort_by: [], having: None, qualify: None }), order_by: [], limit: None, offset: None, fetch: None, locks: [] })]
```

As you can see, `SELECT 123foobar FROM table1` was treated as ``SELECT 123 foobar FROM table1`

**Comment by DiamondMofeng** [comment] 2023-02-06 07:38
Okay, I think it has nothing to do with if some dialect supports column name beginning with numbers. This is simply a bug about ending parsing token early

**Comment by Jefffrey** [comment] 2023-02-06 20:12
I believe this is intended behaviour, at least for Generic/Postgres dialect. Relevant bit of discussion here:

https://github.com/sqlparser-rs/sqlparser-rs/pull/768#discussion_r1058345105

Though some dialects can support having their identifiers begin with a number, such as Hive:

https://github.com/sqlparser-rs/sqlparser-rs/blob/4955863bdf0e9d90e0fff72bca7912b3d20daac2/src/dialect/hive.rs#L23-L28

Though this does cause some issues with parsing numbers, for example exponent parsing does not work (related to above discussion)

Since Hive supports it, same could be enabled for MySql now which has an existing comment about it:

https://github.com/sqlparser-rs/sqlparser-rs/blob/4955863bdf0e9d90e0fff72bca7912b3d20daac2/src/dialect/mysql.rs#L19-L29

**Comment by AviRaboah** [comment] 2023-04-20 06:30
Any update about this issue? do this issue should be fixed in the near future for mysql?

thanks.

**Closed** 2023-04-26 13:27 UTC
